version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: evgen200rom
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: house_prices
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./house_prices.csv:/docker-entrypoint-initdb.d/house_prices.csv
    ports:
      - "5432:5432"

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - /home/evgenii/dockercompose/postgresql-42.7.1.jar:/opt/bitnami/spark/app/jars/postgresql-42.7.1.jar
    ports:
      - "4040:4040"
    depends_on:
      - postgres
    command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]

  spark-worker1:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

  spark-worker2:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

